### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by iowelinux** [rjeczalik/notify#101]
Hi,

Actually this is not an issue however I believe your answer would be really helpful for lots of developers.
Here is a simple code I try to run.

```go
func main() {

	log.Println("fswatch started")
	c := make(chan notify.EventInfo, 1000)

	if err := notify.Watch(".", c, notify.All); err != nil {
		log.Fatal(err)
	}
	defer notify.Stop(c)

	for {
		ei := <-c
		log.Println(ei.Path(), ei.Event().String())
	}
}
```

Nothing is logged.
Do I do something wrong?

**Comment by rjeczalik** [comment]
> Nothing is logged.

What should be logged? Could you `go run -tags debug main.go`, do whatever file operations you're doing and then paste the output here?

**Comment by iowelinux** [comment]
> What should be logged?

As you can see in the code path and event type should be printed using log.Println

Seems like it was some kind of mistake at my side because the same code works now. Sorry for that.
I can detect Remove, Create, Rename events but can't get access events at all.

For instance running the following commands on Linux doesn't output anything:

```bash
cat test
```
nothing.

```perl
#!/usr/bin/perl

open FH, "test";
while (<FH>) {
  print $_;
}
close FH;
```
nothing.

I believe InAccess and InOpen events should be detected in this case. Shouldn't it?
All test were done on Linux 3.10.0 x86_64 kernel

**Comment by rjeczalik** [comment]
`notify.All` is defined as:

```go
const (
    Create = osSpecificCreate
    Remove = osSpecificRemove
    Write  = osSpecificWrite
    Rename = osSpecificRename

    // All is handful alias for all platform-independent event values.
    All = Create | Remove | Write | Rename
)
```

If you want linux-specific events like `notify. InAccess`, you need to pass it additionally.
