### ISSUE TITLE
Build on Windows targeting OSX fails

### ISSUE THREAD

**Issue by markvincze** [rjeczalik/notify#108]
I have an application in which I want to use `rjeczalik/notify`.  
I build this application on a Windows machine for three platforms, Windows, Linux and OSX. If I want to build it for OSX, I get a compilation error.

My build script is doing:
```
$env:GOARCH="amd64"
$env:GOOS="darwin"
go build -o output -i .
```

And the error I get:
```
vendor\github.com\rjeczalik\notify\watcher_fsevents.go:51: undefined: stream
```

If I target Windows (`GOOS="windows"`) or Linux (`GOOS="linux"`), then this problem does not occur.

**Comment by rjeczalik** [comment]
@markvincze Darwin uses CGO so you won't be able to cross-compile it.

**Comment by rjeczalik** [comment]
If you have no other option to build for macOS you can pass `kqueue` build tag to use `kqueue` instead of `FSEvents` as the implementation:

```
go build -tags kqueue -o output -i  .
```

**Comment by markvincze** [comment]
Thanks for the info!

Do you know if kqueue has any significant drawbacks? Does it support recursive watching?

**Comment by rjeczalik** [comment]
@markvincze All the watchers support recursive watching in notify - Windows and macOS natively, Linux and FreeBSD emulated. `kqueue` comes from FreeBSD, so the recursive watching is emulated by notify. With `kqueue` you may run out of fd limits eventually if you're watching a lot of files, bumping `ulimit` may help here.
