### ISSUE TITLE
ld: warning: directory not found for option '-L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib'

### ISSUE THREAD

**Issue by ltzMaxwell** [rjeczalik/notify#120]
go version :1.8.1 , mac version : 10.12.2
build fail , as : 
   ld: warning: directory not found for option '-
 L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib'

**Comment by rjeczalik** [comment]
@ltzMaxwell Do you have command line tools installed? (`xcode-select --install`). If yes, could you add `-x` flag to your build line and paste full output from it?

**Comment by ltzMaxwell** [comment]
fixed after update xcode and command line tool. would you explain this ? thx.

**Comment by rjeczalik** [comment]
@ltzMaxwell notify uses FSEvents under macOS,  FSEvents requires CGO to link with CoreServices, CGO requires clang and CoreServices requires macOS SDK to be installed. 🎉
