### ISSUE TITLE
File creation events not picked with solaris specific events

### ISSUE THREAD

**Issue by imsodin** [rjeczalik/notify#121]
I pass the following events to `Watch`:
```
notify.FileDelete | notify.FileModified | notify.FileRenameTo | notify.FileRenameFrom | notify.FileAttrib
```
Then I create or rename a file in a recursively watched directory. The result is, that I only get events for files that were deleted and files that were renamed (source file). For created files and the destination files during renaming there is no event.
When I do the same thing passing the "generic" events `notify.All`, I get all the events as expected.

I did notice there is no fen/solaris specific event like `notify.FileCreate`, but as file creations are picked up by the generic `notify.All`, it must be capable of detecting file creations. So am I missing something or is this a bug?

**Comment by pblaszczyk** [comment]
https://github.com/rjeczalik/notify/blob/master/watcher_trigger.go#L7

**Comment by imsodin** [comment]
Thanks for the pointer. So if I understand this correctly, when I pass native events I just get plain native events, meaning not create events by design. When I pass the generic events (notify.All) notify does "internal magic" (good enough for me x) ) to provide create events as well.

Can I mix native and generic events to get both `notify.All` and `notify.FileAttrib` events?

**Comment by pblaszczyk** [comment]
Yes: "notify.All | notify.FileAttrib".

**Comment by imsodin** [comment]
Thanks again -> closed.
