### ISSUE TITLE
Does the inotify watch work on android?

### ISSUE THREAD

**Issue by imsodin** [rjeczalik/notify#133]
Is there a reason that the inotify watch is not built on android? Generally the kernel feature should be there, is there any restriction imposed by golang.org/x/sys/unix"?

**Comment by ppknap** [comment]
Hi @imsodin 

We didn't test Android builds. However, the code compiles for this target(`GOOS=android` uses `linux` build tags) so we can expect that inotify watcher works.

Feel free to test it and report any bugs you encounter.

**Comment by imsodin** [comment]
@ppknap Thanks for the feedback, I didn't realize android isn't a build tag - then we would have tested first. Well @Nutomic tried it and it works :)

**Comment by ppknap** [comment]
Glad that it works! 

BTW: there is `android` build tag but it's not necessary when `linux` and `android` impls are identical.
