### ISSUE TITLE
panic: runloop has just unexpectedly stopped

### ISSUE THREAD

**Issue by karalabe** [rjeczalik/notify#139]
This might be related to the Go 1.10 fix PR merged in recently (https://github.com/rjeczalik/notify/pull/136). I've just pulled in the latest code from this repo and our tests on macos began crashing immediately with Go 1.10beta1:

```
panic: runloop has just unexpectedly stopped
goroutine 21 [running]:
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.init.1.func1()
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:69 +0x79
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.init.1
	/Users/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:65 +0x4e
```

**Comment by rjeczalik** [comment]
> and our tests on macos began crashing immediately with Go 1.10beta1

Those tests are the ones from linked issues? Sorry for being lazy, but how to run them?

**Comment by karalabe** [comment]
With that commit reverted, compilation fails due to Go 1.10-s messing with CGO. That being said, it's interesting that the latest code seems to work well for Go 1.9 and before, just breaks on 1.10.

I'll try to make a repro for you, not sure yet what's the simplest package to extract :)

**Comment by karalabe** [comment]
Apparently fixed by https://github.com/rjeczalik/notify/pull/140. Will reopen if the issue resurfaces.
