### ISSUE TITLE
undefined: dispatch in mac 

### ISSUE THREAD

**Issue by c5ms** [rjeczalik/notify#153]
os : darwin.
go : 1.10.1

`../vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:63: undefined: dispatch
../vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:167: undefined: dispatch`

when i compile my program.
it has a error ;

**Comment by ppknap** [comment]
Hey @c5ms!

This doesn't look like the code from current `master` branch. Have you updated your deps? If yes, does the `HEAD` hash starts with `d152f3c`(latest commit)?

**Comment by c5ms** [comment]
sorry , I use dep something wrong .
Thinks .

发自网易邮箱大师

On 05/3/2018 23:19，Pawel Knap<notifications@github.com><mailto:notifications@github.com> wrote：

Hey @c5ms<https://github.com/c5ms>!

This doesn't look like the code from current master branch. Have you updated your deps? If yes, does the HEAD hash starts with d152f3c(latest commit)?

**Comment by c5ms** [comment]
Maybe,you can release a version such as v0.5.0?

**Comment by rjeczalik** [comment]
Just created a tag, see #146. Closing.
