### ISSUE TITLE
Cannot build project for macOS

### ISSUE THREAD

**Issue by x1unix** [rjeczalik/notify#177]
Hello.

I'm trying to build a project on linux for target `darwin amd64` and getting this error:

```
 # github.com/x1unix/gilbert/vendor/github.com/rjeczalik/notify
vendor/github.com/rjeczalik/notify/watcher_fsevents.go:49:11: undefined: stream
```

Are cross-builds supported?

**Comment by rjeczalik** [comment]
Hey @x1unix! It's not possible to cross-compile for darwin from linux, since notify uses CGO on darwin. You'd need to build it on macOS instead.

**Comment by x1unix** [comment]
@rjeczalik thank you for response
