### ISSUE TITLE
Still "under active development"?

### ISSUE THREAD

**Issue by egnor** [rjeczalik/notify#207]
The README for this project says it is "under active development", and positions it as "on steroids" (presumably as opposed to the more widely used `fsnotify` package). Is it still under active development?

**Comment by wdscxsj** [comment]
The latest release is v0.9.2 from 2018, almost 4 years ago. Maybe tag a new version?

**Comment by rjeczalik** [comment]
I removed the outrageous "under active development" note from the readme. Thanks for reporting!
