### ISSUE TITLE
C.FSEventStreamScheduleWithRunLoop(ref, runloop, C.kCFRunLoopDefaultMode) MacOS 13 future remove 

### ISSUE THREAD

**Issue by yantianlei** [rjeczalik/notify#212]
cgo-gcc-prolog:217:2: warning: 'FSEventStreamScheduleWithRunLoop' is deprecated: first deprecated in macOS 13.0 - Use FSEventStreamSetDispatchQueue instead. [-Wdeprecated-declarations]

```
FSEventStreamScheduleWithRunLoop(
  FSEventStreamRef   streamRef,
  CFRunLoopRef       runLoop,
  CFStringRef        runLoopMode) API_DEPRECATED("Use FSEventStreamSetDispatchQueue instead.", macos(10.5, 13.0), ios(6.0,16.0));
```

```
extern void 
FSEventStreamSetDispatchQueue(
  FSEventStreamRef              streamRef,
  dispatch_queue_t __nullable   q)                                      __OSX_AVAILABLE_STARTING(__MAC_10_6, __IPHONE_6_0);
```

Sadly, I tried to modify it and it didn't work

**Comment by josharian** [comment]
It is possible to silence the warning for now with:

```
#cgo CFLAGS: -Wno-deprecated-declarations
```

But that'll obviously only work until it doesn't. :)

I'm game to try to fix the issue properly, or to send that one-line temporary patch, if it'll get reviewed. @rjeczalik?

**Comment by rjeczalik** [comment]
> I'm game to try to fix the issue properly, or to send that one-line temporary patch, if it'll get reviewed. @rjeczalik?

@josharian You have my axe 🫡

**Comment by josharian** [comment]
I started on this and have a `dispatch_queue_t`-based implementation working, but I need to read some more docs to make sure it is actually correct, not just accidentally correct. :) Meanwhile, I sent #214 as preliminary cleanup to make all the tests pass.
