### ISSUE TITLE
collect watchpoints when underlying watch was removed outside notify

### ISSUE THREAD

**Issue by rjeczalik** [rjeczalik/notify#69]
Currently it's not possible to call `notify.Watch` on a path that was already watched, but the watch was invalidated by delete of a file / directory, assuming the user did not clean all his watchpoints by calling `notify.Stop`.

Listen for Delete events for both watchpoint tree implementations and mark such watchpoint as inactive. On subsequent `notify.Watch` on that path reset the watch to its previous state.

**Comment by rjeczalik** [comment]
The issue is two-fold - it won't work perfectly across platforms as Windows does not notify about removed watches:

```
// TODO(pknap) link or it didn't happen
```

The most proper way to deal with this is to set a watchpoint on a path which is guaranteed to not be gone, when we do care to receive events for whole lifetime of our application (those paths being equivalent to `%userprofile%`, `$GOPATH`, `$TMPDIR` etc.).

If for some reason we still need to maintain watcher lifetime to ensure underlying watch is not stopped outside notify, the solution is to listen on `Delete` event, call `Stop` on the listening channel and call `Watch` the path again when we know it's back (most likely by watching a priori its parent for `Create`). However it's so cumbersome to implement, both by the user or by notify itself, that I doubt anyone will need it. Moreover it would create unnecessary overhead, as every path would need to be implicitly watched for `Delete` event as well.

**Comment by mauricioabreu** [comment]
I guess this is exactly the problem I am having on #171 It looks like the solution here is the one you mentioned.
