### ISSUE TITLE
inotify: support for watcher behavior masks 

### ISSUE THREAD

**Issue by ppknap** [rjeczalik/notify#71]
This functionality was disabled due to the problems with multiple chans which need different watcher behavior:

Example:
```go
// ...
// Watch InCreate events in current working directory.
notify.Watch(".", ch1, notify.InCreate) 
// ...
// Watch InDelete events triggered **ONLY on directories** in current working folder.
notify.Watch(".", ch2, notify.InDelete, notify.InOnlydir)
```

**Comment by rjeczalik** [comment]
The same story for FSEvents:

```go
notify.Watch(".", c, notify.FSEventsRemoved, notify.FSEventsIsDir)
```

The problem with `notify.Watch(".", c, notify.InDelete, notify.InOnlydir)` is the events are exclusive, if a watchpoint has one channel listening only for `InDelete` and second for `InDelete | InOnlyDir`, the `InDelete | InOnlyDir` event will not get dispatched to the former channel.

Additionally inotify says that `IN_ISDIR` is one of special flags, not events, so I would not bother to support it.
