### ISSUE TITLE
Does not resolve relative symlinks properly

### ISSUE THREAD

**Issue by hlandau** [rjeczalik/notify#83]
If the watcher is asked to monitor a path /a/b/c/d/e/f, where c is a symlink to (literally) x/y/z, this should be resolved to /a/b/x/y/z/d/e/f. Instead, it seems to get resolved to /x/y/z/d/e/f.

**Comment by rjeczalik** [comment]
@hlandau Yup, it erroneously assumes [here](https://github.com/rjeczalik/notify/blob/master/util.go#L91) the link is absolute.
