### ISSUE TITLE
Notify doesn't fire events when a folder changes in Mac OS X Finder

### ISSUE THREAD

**Issue by teechap** [rjeczalik/notify#84]
I'm playing around with notify and I'm not sure if I've found a bug in Mac OS 10.10.4. Here's a simple program I'm running:
```go
package main

import "github.com/rjeczalik/notify"
import "fmt"

func main() {
	// Make the channel buffered to ensure no event is dropped. Notify will drop
	// an event if the receiver is not able to keep up the sending pace.
	c := make(chan notify.EventInfo, 1)

	// Set up a watchpoint listening on events within current working directory.
	// Dispatch each create and remove events separately to c.
	if err := notify.Watch(".", c, notify.Create, notify.Remove); err != nil {
		fmt.Println("Error:", err)
	}
	defer notify.Stop(c)

	// Block until an event is received.
	for ie := range c {

	 fmt.Println("Got event:", ie)

	}
}
```
When I create and delete files using Terminal (i.e. ```echo hello > newfile.txt``` and ```rm -rf newfile.txt```, the channel reports events fine. However, when I create a file and click "Move to Trash" in Finder, no event gets fired off. Do you know why?

**Comment by rjeczalik** [comment]
> However, when I create a file and click "Move to Trash" in Finder, no event gets fired off. Do you know why?

Hey @teechap! Sure, the file is *moved* to trashed, so you'd need to also watch for the move events - `notify.Rename`.

**Comment by techapman** [comment]
I'm not very familiar with the FSEvents API, but I'm curious why a "move" event is called "rename." Do you know a good resource to learn the quirks of the API? I would never guess that's how it does things.

**Comment by rjeczalik** [comment]
@techapman The move event is called after `rename` in kqueue, FSEvents and RearDirectoryChangesW and after `move` in inotify, so the former is used as it is more widespread across platforms.

The notify API is best to learn from [it's godoc](https://godoc.org/github.com/rjeczalik/notify#pkg-constants). Each os-level filesystem notification is documented:

- kqueue in this [man page](https://www.freebsd.org/cgi/man.cgi?query=kqueue&sektion=2)
- inotify in this [man page](http://linux.die.net/man/7/inotify)
- FSEvents in the [Apple Developer's documentation](https://developer.apple.com/library/mac/documentation/Darwin/Reference/FSEvents_Ref/)
- ReadDirectoryChangesW in [Windows Dev Center](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365465(v=vs.85).aspx)

And obviously if you have any questions then issues are a good place, as we have no dedicated mailing list atm.
