### ISSUE TITLE
Missing events when creating files by bulk

### ISSUE THREAD

**Issue by sent-hil** [rjeczalik/notify#85]
Hey Rafal, I'm running into a weird issue with watching, where lot of events are dropped when the files are created in a rapid succession, ie using `for f in {0..10}; do echo $f > "$f.txt"; done`

Here's the code I'm using:
```
package main

import (
        "github.com/rjeczalik/notify"
        "log"
)

func main() {
       c := make(chan notify.EventInfo)
        if err := notify.Watch("<folder>", c, notify.All); err != nil {
            log.Fatal(err)
        }
        defer notify.Stop(c)

        var index = 0
        for {
                ei := <-c
                index += 1
                if ei.Event() == notify.Create{
                        log.Println("Got event:", ei, index)
                }
        }
}
```

I tried the same with `fsnotify` and I'm not noticing any drop there:

```
package main

import (
        "gopkg.in/fsnotify.v1"
        "log"
)

func main() {
        watcher, err := fsnotify.NewWatcher()
        if err != nil {
            log.Fatal(err)
        }
        defer watcher.Close()

        var index = 0
        done := make(chan bool)
        go func() {
            for {
                select {
                case event := <-watcher.Events:
                    if event.Op&fsnotify.Write == fsnotify.Write {
                        index += 1
                        log.Println("modified file:", event.Name, index)
                    }
                case err := <-watcher.Errors:
                    log.Println("error:", err)
                }
            }
        }()

        if err = watcher.Add("<folder>"); err != nil {
            log.Fatal(err)
        }
        <-done
}
```

If I added a bit of sleep (0.1s) between file creation, all the events are received. I tested it on Ubuntu (Koding VM).

Regards.

**Comment by rjeczalik** [comment]
Hey, will look into it. There's a `debug` tag which should hint where the events are lost - probably it's the dispatch tree.

```
~ $ go build -tags debug -o testcase main.go
```

**Comment by ppknap** [comment]
Hi all! 

Actually, this is not a bug. @sent-hil you need to provide a buffered channel to `Watch` function:

 ```go
c := make(chan notify.EventInfo, 16) // Or any other arbitrary chosen value.
if err := notify.Watch("<folder>", c, notify.All); err != nil {
  log.Fatal(err)
}
defer notify.Stop(c)
```

Rafal, we haven't been contributing to notify for a long time.. Maybe it's time to do something with it? :smile:

**Comment by rjeczalik** [comment]
> you need to provide a buffered channel

Oh, true, the doc should be more clear about it.

@ppknap There's still a number of bugs to sort out first - #80, #82, then major feature - watch recovery for #76 and filtering #79. Also refactoring needs to be done also.

I can prepare a doc for it later tomorrow.

**Comment by sent-hil** [comment]
@rjeczalik @ppknap ah got it. I tried it again with a buffered channel and it seems to not drop the events anymore. How would you recommend setting the buffered channel size so the events are never dropped regardless of event rate? For my use case I've no idea what the event rate will be (using this pkg as part of an binary that's distributed to users), so I'm not sure about the size.

**Comment by rjeczalik** [comment]
@sent-hil E.g. you can queue the events yourself, so none is dropped:

https://gist.github.com/rjeczalik/7faa93691e6da35b1f84

Question is, if it makes sense to queue the events when the receiver does not keep up with processing them - sometimes you may want to coalesce them first.

**Comment by Forkest** [comment]
Of course it makes sense! Dropping events is usually irresponsible, it desynchronizes the state in the app with the state on the disk, and you aren't even notified of this fact. I can't imagine what are you using fsevents for, if you are allowing them to be dropped. That's an absolutely normal situation when a disk periodically has a peak write load, and that's not a reason to drop events. Perhaps, yes, it might make sense to coalesce them, but that's a different story.

**Comment by rjeczalik** [comment]
@Forkest :+1: Will get that queueing eventually implemented, stay tuned :-)

**Comment by Forkest** [comment]
That's good!

You may want to consider the possibility of using InfiniteChannel from https://github.com/eapache/channels or maybe https://rogpeppe.wordpress.com/2010/02/10/unlimited-buffering-with-low-overhead/

**Comment by rjeczalik** [comment]
@Forkest Surely will look into this, thanks for the links!
