### ISSUE TITLE
Notify doesn't work for CIFS-mounted folders in linux/OSX

### ISSUE THREAD

**Issue by piotrrojek** [rjeczalik/notify#87]
The possible solution would be polling, so it's related to https://github.com/rjeczalik/notify/issues/35.

**Comment by ppknap** [comment]
Hi @piotrrojek !

None of the os watchers work on NTP filesystems, also affects Windows, FreeBSD and any other platforms. If you want to have a shot at implementing this, look at the API of non-recursive watcher implementation as [watcher_inotify.go](watcher_inotify.go) or [watcher_kqueue.go](watcher_kqueue.go).

As noted, closing is a duplicate.

Thanks for contributing!
