### ISSUE TITLE
Windows no target on rename

### ISSUE THREAD

**Issue by swynter-ladbrokes** [rjeczalik/notify#89]
Greetings

Super simple code

```
package main
import (
    "fmt"
    "github.com/rjeczalik/notify"
)
func main() {
    c := make(chan notify.EventInfo, 1)
    if err := notify.Watch("c:\\temp\\...", c, notify.All); err != nil {
        panic(err)
    }
    defer notify.Stop(c)
    for ei := range c {
        fmt.Printf("%s %#v\n", ei, ei)
    }
}
```

When I rename a file or directory in c:\temp I get the rename, but no target "create"

```
echo "hi" > hello
notify.Create: "c:\temp\hello" &notify.event{pathw:[]uint16{0x63, 0x3a, 0x5c, 0x74, 0x65, 0x6d, 0x70, 0x0}, name:"hello", ftype:0x1, action:0x1, filter:0xf00000, e:0x100000}
notify.Write: "c:\temp\hello" &notify.event{pathw:[]uint16{0x63, 0x3a, 0x5c, 0x74, 0x65, 0x6d, 0x70, 0x0}, name:"hello", ftype:0x0, action:0x3, filter:0xf00000, e:0x400000}

mkdir foo
notify.Create: "c:\temp\foo" &notify.event{pathw:[]uint16{0x63, 0x3a, 0x5c, 0x74, 0x65, 0x6d, 0x70, 0x0}, name:"foo", ftype:0x2, action:0x1, filter:0x4f00000, e:0x100000}

mkdir foo\bar
notify.Create: "c:\temp\foo\bar" &notify.event{pathw:[]uint16{0x63, 0x3a, 0x5c, 0x74, 0x65, 0x6d, 0x70, 0x0}, name:"foo\\bar", ftype:0x2, action:0x1, filter:0x4f00000, e:0x100000}

ren hello bye
notify.Rename: "c:\temp\hello" &notify.event{pathw:[]uint16{0x63, 0x3a, 0x5c, 0x74, 0x65, 0x6d, 0x70, 0x0}, name:"hello", ftype:0x1, action:0x4, filter:0xf00000, e:0x800000}

ren foo\bar foo\bleh
notify.Rename: "c:\temp\foo\bar" &notify.event{pathw:[]uint16{0x63, 0x3a, 0x5c, 0x74, 0x65, 0x6d, 0x70, 0x0}, name:"foo\\bar", ftype:0x2, action:0x4, filter:0x4f00000, e:0x800000}
```

Linux gives me a rename->create
OSX gives me rename->rename

**Comment by swynter-ladbrokes** [comment]
Right after I posted this, I wondered if it was some sort of timing issue and increased the channel buffer from 1 to 2, and now I get two rename events.

Trap for young players? :D

**Comment by rjeczalik** [comment]
> Trap for young players?
@swynter-ladbrokes: This is one way to put it - related to https://github.com/rjeczalik/notify/issues/85. The idea to off-load the buffering logic to the user was borrowed from [(os.Signal).Notify](https://golang.org/pkg/os/signal/#Notify). We want to take it over at some point.

**Comment by ppknap** [comment]
No, It isn't a trap. Examples have `1`-sized buffer just to show that you need to specify its size in order to not drop the events. Maybe we should set this to some larger value to avoid issues like this?

**Comment by rjeczalik** [comment]
> Maybe we should set this to some larger value to avoid issues like this?

I think it's not needed for now.
